theme: jekyll-theme-cayman
title: "Yair Goldshtein"
description: Lecturer in the Department of Software and Computer Engineering, Lev Academic Center, Jerusalem
show_downloads: false
github:
   is_project_page: false
